- filename: J155 - Undertaking and Acceptance of Masters Directions.pdf
  fields:
    deceased id: Text4-1
    deceased full name: Text2
    estate number: Text1
    deceased date of death: Text3
    deceased district: Text5
    applicant full name:
      - Text6
      - Text13
    applicant id: Text7-1
    applicant relationship to deceased: Text8
    applicant residential address line 1: Text9-1
    applicant residential address line 2: Text9-2
    applicant residential address line 3: Text9-3
    applicant postal address line 1: Text10-1
    applicant postal address line 2: Text10-2
    applicant postal address line 3: Text10-3
    applicant home telephone area: Text9-4
    applicant home telephone remainder: Text9-5
    applicant work telephone area: Text10-4
    applicant work telephone remainder: Text10-5
    agent name: Text11-1
    agent postal address: Text11-2
    agent telephone area: Text11-3
    agent telephone remainder: Text11-4

- filename: J190 - Acceptance of Trust as Executor.pdf
  fields:
    estate number: Estate No
    applicant full name:
      - lWe full names and surname
      - PRINT NAME AND SURNAME
    applicant business address line 1: Business address1
    applicant business address line 2: Business address2
    applicant business address line 3: Business address3
    applicant work telephone: "0"
    applicant id: ID
    applicant relationship to deceased: Relationship to deceased
    deceased full name: Full names and surname
    deceased date of birth: Date of birth
    deceased date of death: Date of death
    deceased id: Identity No
    deceased income tax ref. no: Income tax ref No
    deceased district: District in which deceased normally resided
    surviving spouse name: Name of surviving spouse in case of deceased having been a married woman
    signed at: signed at
    current day and month: signed on
    current year: year
    bond of security: rand
    applicant residential address: contemplated in the Administration of Estates Act No 66 of 1965 as amended at not PO box number

- filename: J192 - Next of Kin Affidavit.pdf
  fields:
    applicant full name:
      - I
      - Print Name and Surname
    applicant residential address: of 1
    signed at: at
    current day: "0"
    current month: day of
    current year: year
    commissioner of oaths: MagistrateJustice of the PeaceCommissioner of Oaths
    appointed area: Area for which appointed
    state office held: If appointment is held ex officio state office held
    deceased full name:
    deceased place of death: died at
    deceased date of death: date
    surviving spouse name: Names of relatives and degree of relationship1  Surviving spouse
    children info: Names of relatives and degree of relationship2 Children and date of their birth Also state names of predeceased children and their dates of death
    father of deceased: Names of relatives and degree of relationshipIgnore questions 3 4 and 5 if the deceased left children or descendants 3 Father of deceased Mother of deceased
    mother of deceased: Names of relatives and degree of relationshipIgnore questions 3 4 and 5 if the deceased left children or descendants 3 Father of deceased Mother of deceased
    sibling info: |-
      Names of relatives and degree of relationshipIgnore questions 4 and 5 if the parents are both alive 4  Brothers and sisters of the deceased  State whether full or half blood and their addresses and dates of birth State the name of the stepparent of half b\
      rothers and half sisters
    dead sibling info: Names of relatives and degree of relationship5 Names of brothers and sisters who are dead date of deaths and names addresses and dates of birth of their children if any

- filename: J243 - Estate Inventory.pdf
  fields:
    deceased full name: name
    surviving spouse name: Full name of surviving spouse in a case where spouses were married in community of property
    surviving spouse address: Address of surviving spouse
    massed estate: Massed estate of
    minors under tutorship: Full names of minors under tutorship or person in respect of whose property letters of curatorship have been granted
    minor address: Full address
    applicant full name:
      - lfull name
      - name and surname
    applicant residential address: of full address
    deceased place of death: premises at
    signed at: Place
    current date: Date

- filename: J294 - Death Notice.pdf
  fields:
    deceased surname: "1"
    deceased first name: "2"
    deceased id: "0"
    deceased population group: "1_2"
    deceased nationality: 5 Nationality
    deceased occupation: "2_2"
    deceased ordinary residence: 7 Ordinary places of residence during the 12 months prior to death and the Provinces
    deceased date of birth: 9 Place of birth
    deceased place of birth: 8 Date of birth
    deceased date of death: 10 Date of death
    deceased will: 11Has the deceased left a will
    deceased marital status: 12 Marital status at time of death
    deceased place of marriage: 13 If married place where married
    surviving spouse name: 14 Full names of surviving spouse
    surviving spouse id: and hisher IDPassport number
    marriage info: 15 State whether marriage was in or out of community of propertywhether accrual system is applicable
    predeceased or divorced spouse names: a Names of predeceased spouses andor divorced spouses state opposite name of each whether predeceased or divorced
    predeceased spouse date of death: b Date of death of predeceased spouses
    names of children of deceased: if that be the case the full names of such issue 1
    father of deceased: a Father
    mother of deceased: b Mother
    applicant full name and address: 19 Name and address of person signing the death notice
    capacity: 20 Capacity
    signatory presence at death: 21 a Was the signatory present at the deceaseds death
    signatory identification of deceased: b If the answer to the previous question is no did the signatory identify the deceased after his death
    current date:
    current day:
    current month:
    current year: in the year

- filename: Marital Status Declaration.pdf
  fields:
    applicant full name: I
    applicant residential address: Of Address 1
    deceased full name: Deseaced
    known since: Was well known to me since
    deceased number of wives: nr1
    deceased number of customary unions: nr2
    signed at: Signed and sworn toaffirmed before me at
    current day: This
    current month: Day of
    current year: in the year
    appointed area: Area for which appointed

- filename: Nomination to Act as Executor or Masters Representative.pdf
  fields:
    deceased full name: Estate late
    person nominated: I  We the undersigned hereby nominates
    surviving spouse name: NameRow1
    relationship to deceased: Relationship  CapacityRow1
    current date: DateRow1

- filename: Reporting Affidavit.pdf
  fields:
    applicant full name: I
    deceased full name:
      - estate
      - the late
    answer1: Answer
    answer2: Answer_2
    answer3: Answer_3
    signed at: Signed and sworn toaffirmed before me at
    current day: This
    current month: Day of
    current year: in the year
    appointed area: Area for which appointed
