file1:
    filename: J155 - Undertaking and Acceptance of Masters Directions.pdf
    fullname: 
    id: 
    url: 

file2:
    filename: J190 - Acceptance of Trust as Executor.pdf
    fullname: 
    id: 
    url: 

file3: 
    filename: J243 - Estate Inventory.pdf
    fullname: 
    Surviving spouse full name: 
    Surviving spouse address: 
    Date: 
    Name and surname: 

file4: 
    filename: J294.-.Death.Notice.pdf
    id: 
    Surname: 
    First Names: 
    Nationality: 
    Occupation: 
    Date of birth: 
    Place of birth: 

file5: 
    filename: Marital Status Declaration.pdf
    fullname: 
    Address: 
    DeceasedName: 
    KnownSince: 
    SignedAndSworn: 

file6: 
    filename: Nomination to Act as Executor or Masters Representative.pdf
    Estate late: 
    nominates: 
    NameRow1: 
    Relationship  CapacityRow1: 
    DateRow1: 

file7: 
    filename: Reporting Affidavit.pdf
    fullname: 
    estate: 
    Answer1: 
    Answer2: 
    Answer3: 
    SignedAndSworn: 